
[workspace]

resolver = "2"

members = [
    "crates/core",
    "crates/lexer",
    "crates/parser",
    "crates/interpreter",
    "crates/diagnostics",
    "cli",
]

[profile.release]
lto = true
strip = true
