
[workspace]

resolver = "2"

members = [
    "crates/core",
    "crates/lexer",
    "crates/parser",
    "crates/ir",
    "crates/interpreter",
    "crates/diagnostics",
    "cli",
    "xtask",
    "crates/codegen_js",
    "crates/typeck",
    "crates/reactivity",
    "fuzz",
]

[profile.release]
lto = true
strip = true
