name: CI - xtask golden + tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-goldens-and-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Build and run xtask golden check
        run: |
          cargo install --locked cargo-make || true
          cargo run -p xtask -- gen-golden --check

      - name: Run tests
        run: cargo test --all --locked
