name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - name: Build
        run: cargo build --all
      - name: Run tests
        run: cargo test --all --quiet

  metrics:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - name: Build CLI release
        run: cargo build -p cli --bin art
      - name: Run metrics script
        run: |
          chmod +x scripts/run_metrics.sh || true
          mkdir -p artifacts
          # run the script which will write artifacts/metrics.json
          bash scripts/run_metrics.sh cli/examples/99_weak_unowned_demo.art artifacts/metrics.json || true
      - name: Upload metrics artifact
        uses: actions/upload-artifact@v4
        with:
          name: metrics
          path: artifacts/metrics.json
name: CI


