name: Phase 10 — IR / JIT pipeline checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      jit_smoke:
        description: 'Run optional JIT smoke job (requires LLVM)'
        required: false

jobs:
  test-and-golden:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y pkg-config cmake
      - name: Run cargo test (workspace)
        run: cargo test --workspace
      - name: Run xtask irgen --check
        run: cargo run -p xtask -- irgen --check

  jit-smoke:
    if: ${{ github.event.inputs.jit_smoke == 'true' }}
    runs-on: ubuntu-latest
    needs: test-and-golden
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install LLVM deps
        run: sudo apt-get update && sudo apt-get install -y llvm-dev clang
      - name: Build jit with feature
        run: cargo build -p jit --features=jit
