name: xtask irgen --check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  gen-golden-check:
    runs-on: ubuntu-latest
    name: Run xtask irgen --check
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - name: Run xtask irgen --check
        run: cargo run -p xtask -- irgen --check
